[build]
  command = "npm run lint && npm run build"
  publish = ".next"

[build.environment]
[context.production.branch-deploy]
  command = "mv robots-disallow.txt robots.txt"
[context.production]
  command = "mv robots-production.txt robots.txt"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/blog/entry/*"
  to = "/blog/:splat"
  status = 301
  force = true
